export const CINEMATIC_QUOTES = [
  '"You either die a hero or you live long enough to see yourself become the villain." — The Dark Knight',
  '"Which would be worse: to live as a monster, or to die as a good man?" — Shutter Island',
  '"Some men just want to watch the world burn." — The Dark Knight',
  '"We buy things we don\'t need, to impress people we don\'t like." — Fight Club',
  '"It\'s only after we\'ve lost everything that we\'re free to do anything." — Fight Club',
  '"The greatest trick the devil ever pulled was convincing the world he didn\'t exist." — The Usual Suspects',
  '"Get busy living, or get busy dying." — The Shawshank Redemption',
  '"All those moments will be lost in time, like tears in rain." — Blade Runner',
  '"Every man dies, not every man really lives." — Braveheart',
  '"Do, or do not. There is no try." — Star Wars: Episode V - The Empire Strikes Back',
  '"Our lives are defined by opportunities, even the ones we miss." — The Curious Case of Benjamin Button',
  '"A man who doesn\'t spend time with his family can never be a real man." — The Godfather',
  '"The saddest thing in life is wasted talent." — A Bronx Tale',
  '"యుద్ధం అంటే మన ఎదుటి వాడిని చంపడం కాదు... మనలోని మృగాన్ని చంపుకోవడం." — కంచె',
  '"ఎవడు ఎవరినీ చంపలేడు... ఎవరి చావు వాళ్ళదే." — అతడు',
  '"నిజం చెప్పే ధైర్యం లేకపోతే, అబద్ధం చెప్పే హక్కు లేదు." — అతడు',
  '"ప్రాణం విలువ తెలియాలంటే ప్రాణాలు తీసే వాడివి కాదు... ప్రాణాలు పోసే వాడివి అవ్వాలి." — గమ్యం',
  '"దేవుడు గుడిలో ఉండడు... మనుషుల్లో ఉంటాడు." — ఖలేజా',
  '"నాతో నేను రోజు చేసే యుద్ధంలో... ఈరోజు నేనే గెలిచా." — జెర్సీ',
  '"ధర్మం గెలవాలంటే యుద్ధం చెయ్యాలి, యుద్ధం గెలవాలంటే ధర్మంగా ఉండాలి." — బాహుబలి: ది కంక్లూజన్',
  '"बाबूमोशाय, जिंदगी बड़ी होनी चाहिए, लंबी नहीं।" — आनंद',
  '"कहीं पर पहुंचने के लिए कहीं से निकलना बहुत ज़रूरी होता है।" — ये जवानी है दीवानी',
  '"हम सब तो रंगमंच की कठपुतलियां हैं जिनकी डोर ऊपर वाले की उंगलियों में बंधी है।" — आनंद',
  '"जो हारकर जीतता है उसे बाज़ीगर कहते हैं।" — बाज़ीगर',
  '"इंसान का कर्तव्य होता है कोशिश करना... कामयाबी नाकामी सब उसके हाथ में है।" — शोले'
];
